<a href="https://colab.research.google.com/github/DS3001/group10/blob/main/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
! git clone https://github.com/DS3001/group10

Cloning into 'group10'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 36 (delta 12), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (36/36), 4.67 MiB | 9.07 MiB/s, done.
Resolving deltas: 100% (12/12), done.

In [5]:
# importing pandas and numpy for data cleaning
import pandas as pd
import numpy as np

In [6]:
# the raw file is found in the git repo
df = pd.read_csv("./group10/raw_gss_data.csv")
display(df)

,year,age,sex,race,polviews,confinan,conbus,conclerg,coneduc,confed,...,contv,conjudge,consci,conlegis,conarmy,conpharvac,conpharvacy,confedvac,confedvacy,conhlth
0,1972,23.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1972,70.0,male,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1972,48.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1972,27.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1972,61.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72392,2022,22.0,female,white,extremely liberal,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72393,2022,29.0,female,white,"moderate, middle of the road",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72394,2022,32.0,male,white,slightly liberal,only some,only some,only some,a great deal,only some,...,only some,hardly any,a great deal,a great deal,a great deal,NaN,NaN,NaN,NaN,NaN
72395,2022,49.0,female,white,slightly liberal,only some,a great deal,only some,a great deal,a great deal,...,only some,only some,a great deal,only some,a great deal,NaN,a great deal,NaN,a great deal,a great deal of confidence
72396,2022,50.0,male,white,liberal,only some,only some,only some,only some,only some,...,hardly any,hardly any,a great deal,only some,a great deal,NaN,a great deal,NaN,a great deal,NaN

In [7]:
# the raw data was already subsections to only included the columns we wanted to look at
df.columns

Index(['year', 'age', 'sex', 'race', 'polviews', 'confinan', 'conbus',
       'conclerg', 'coneduc', 'confed', 'conlabor', 'conpress', 'conmedic',
       'contv', 'conjudge', 'consci', 'conlegis', 'conarmy', 'conpharvac',
       'conpharvacy', 'confedvac', 'confedvacy', 'conhlth'],
      dtype='object')

In [8]:
# weird thing happens and there are 7 rows with just the column names
# this shows all the rows like this so I could see which indexes to drop
df.loc[df['polviews'] == 'polviews']

# Dropping all the rows with the column names instead of values
df = df.drop([10000,20001,30002,40003,50004,60005,70006])
df.loc[df['polviews'] == 'polviews']

Empty DataFrame
Columns: [year, age, sex, race, polviews, confinan, conbus, conclerg, coneduc, confed, conlabor, conpress, conmedic, contv, conjudge, consci, conlegis, conarmy, conpharvac, conpharvacy, confedvac, confedvacy, conhlth]
Index: []

[0 rows x 23 columns]

In [9]:
# Looking at the unique columns in the polical views column to see what the scale is
print(df['polviews'].unique())

[nan 'moderate, middle of the road' 'slightly conservative' 'conservative'
 'liberal' 'extremely conservative' 'slightly liberal' 'extremely liberal']

In [10]:
# This mapping is based on codebook. The scale was from extremely liberal to extremely conservative
# We decided the numerical values would be easier to use for graphs because long string values on the a-xais makes a graph harder to read
# often the print has to be too small to read and for the confidence scales, a numerical values is intutive to people
df['polviews'] = df['polviews'].map({'extremely liberal': 1, 'liberal': 2, 'slightly liberal': 3, 'moderate, middle of the road':4,
                                     'slightly conservative':5, 'conservative':6, 'extremely conservative':7})

# I looked at the value counts to make sure all the variables were converted to numeric values
df['polviews'].value_counts()

4.0    23992
5.0     9596
6.0     9361
3.0     7900
2.0     7623
7.0     2165
1.0     2081
Name: polviews, dtype: int64

In [11]:
# printed unique out to confirm that all the values were numeric or nan
print(df['polviews'].unique())

[nan  4.  5.  6.  2.  7.  3.  1.]

In [12]:
# The maping of conhlth varaible is different than the polical views mapping, so
# I printed this out to see them all
print(df['conhlth'].unique())
# I used the codebook to find the correct numerical mappings of complete confidence to no confidence at all
df['conhlth'] = df['conhlth'].map({'complete confidence': 1, 'a great deal of confidence': 2, 'some confidence': 3,
                                   'very little confidence':4,'no confidence at all':5})
df['conhlth'].value_counts()

[nan 'some confidence' 'very little confidence' 'no confidence at all'
 'a great deal of confidence' 'complete confidence']

3.0    544
4.0    227
2.0    225
5.0     91
1.0     60
Name: conhlth, dtype: int64

In [13]:

print(df['confedvacy'].unique())
# the most of rest of them have the same mappings based on the codebook
# I noticed the only different variable was confedvacy, so this is handled in a later code chunk

[nan 'hardly any' 'only some' 'a great deal']

In [14]:
# these are all the varibles with the mapping a great deal to hardly any on the confidence scale
cols = ['confinan', 'conbus',
       'conclerg', 'coneduc', 'confed', 'conlabor', 'conpress', 'conmedic',
       'contv', 'conjudge', 'consci', 'conlegis', 'conarmy', 'conpharvac',
       'conpharvacy', 'confedvac', 'confedvacy']

# as they are all the same mapping I used a loop
# I then printed out all the unique values in the newly mapped variable to make sure it was just 1,2,3 and nans
for i in cols:
  df[i] = df[i].map({'a great deal': 1, 'only some': 2, 'hardly any': 3})
  print(df[i].unique())

[nan  1.  2.  3.]
[nan  2.  1.  3.]
[nan  3.  1.  2.]
[nan  1.  3.  2.]
[nan  2.  1.  3.]
[nan  2.  3.  1.]
[nan  2.  3.  1.]
[nan  2.  1.  3.]
[nan  3.  2.  1.]
[nan  1.  2.  3.]
[nan  2.  1.  3.]
[nan  2.  1.  3.]
[nan  1.  2.  3.]
[nan  2.  3.  1.]
[nan  2.  1.  3.]
[nan  2.  3.  1.]
[nan  3.  2.  1.]

In [15]:
# The year values are all strings
print(df['year'].unique())
# Coercing these values to numbers
df['year'] = pd.to_numeric(df['year'], errors='coerce')
# You can see it worked because the values are no longer in quotes
print(df['year'].unique())

['1972' '1973' '1974' '1975' '1976' '1977' '1978' '1980' '1982' '1983'
 '1984' '1985' '1986' '1987' '1988' '1989' '1990' '1991' '1993' '1994'
 '1996' '1998' '2000' '2002' '2004' '2006' '2008' '2010' '2012' '2014'
 '2016' '2018' '2021' '2022']
[1972 1973 1974 1975 1976 1977 1978 1980 1982 1983 1984 1985 1986 1987
 1988 1989 1990 1991 1993 1994 1996 1998 2000 2002 2004 2006 2008 2010
 2012 2014 2016 2018 2021 2022]

In [16]:
# Age also came in as a string value so we followed the same coercing process
print(df['age'].unique())
df['age'] = pd.to_numeric(df['age'], errors='coerce')
print(df['age'].unique())

['23.0' '70.0' '48.0' '27.0' '61.0' '26.0' '28.0' '21.0' '30.0' '56.0'
 '54.0' '49.0' '41.0' '24.0' '62.0' '46.0' '57.0' '58.0' '71.0' '53.0'
 '42.0' '20.0' '25.0' '78.0' '35.0' '51.0' '76.0' '39.0' '64.0' '50.0'
 '40.0' '43.0' '37.0' '22.0' '31.0' '52.0' '47.0' '45.0' '68.0' '63.0'
 '19.0' '55.0' '44.0' '34.0' '36.0' '74.0' '69.0' '29.0' '67.0' '75.0'
 '38.0' '73.0' '84.0' '82.0' '72.0' '59.0' '33.0' '81.0' '65.0' '32.0' nan
 '60.0' '80.0' '66.0' '77.0' '18.0' '79.0' '83.0' '85.0' '88.0' '87.0'
 '89.0' '86.0']
[23. 70. 48. 27. 61. 26. 28. 21. 30. 56. 54. 49. 41. 24. 62. 46. 57. 58.
 71. 53. 42. 20. 25. 78. 35. 51. 76. 39. 64. 50. 40. 43. 37. 22. 31. 52.
 47. 45. 68. 63. 19. 55. 44. 34. 36. 74. 69. 29. 67. 75. 38. 73. 84. 82.
 72. 59. 33. 81. 65. 32. nan 60. 80. 66. 77. 18. 79. 83. 85. 88. 87. 89.
 86.]

In [17]:
# We kept sex as a string value because there are only two option so making a mapping to a numerical value did not seem necessary
print(df['sex'].unique())

['female' 'male' nan]

In [18]:
# The same thing with race, we did not think a numerical mapping would be helpful
# Also assigning a numerical value to race implies a hierarchy which is a very problematic data coercion
print(df['race'].unique())

['white' 'black' 'other' nan]

In [19]:
# Newly cleaned data
display(df)

,year,age,sex,race,polviews,confinan,conbus,conclerg,coneduc,confed,...,contv,conjudge,consci,conlegis,conarmy,conpharvac,conpharvacy,confedvac,confedvacy,conhlth
0,1972,23.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1972,70.0,male,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1972,48.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1972,27.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1972,61.0,female,white,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72392,2022,22.0,female,white,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72393,2022,29.0,female,white,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72394,2022,32.0,male,white,3.0,2.0,2.0,2.0,1.0,2.0,...,2.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
72395,2022,49.0,female,white,3.0,2.0,1.0,2.0,1.0,1.0,...,2.0,2.0,1.0,2.0,1.0,NaN,1.0,NaN,1.0,2.0
72396,2022,50.0,male,white,2.0,2.0,2.0,2.0,2.0,2.0,...,3.0,3.0,1.0,2.0,1.0,NaN,1.0,NaN,1.0,NaN

In [20]:
df.to_csv("./group10/clean_gss_data.csv", index=False)
# outputed to a new csv file so we still have a copy of the raw data in the repo
# Also note that the raw data came in with all the nans already filled in
# This meant we could not offer any distinction between did not answer and no applicable which is why there was no data cleaning for emtpy values